# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Your awesome title
email: your-email@domain.com
description: Write an awesome description for your new site here
baseurl: "/Gravity" # the subpath of your site, e.g. /blog
url: "http://theme.jekyllwriter.com" # the base hostname & protocol for your site
permalink: /:year/:month/:day/:title/
twitter_username: jekyllwriter
github_username:  jekyllwriter

# Build settings
markdown: kramdown
